name: Build Docs

on:
  push:
    branches: [v3.0]
  pull_request: ~

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Run build command
        run: docker compose run --rm read-the-docs-builder

      - name: Check build
        run: cat _build/html/guides.html

      - name: save site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: _build/html
